// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP32C6

#include "ui.h"

lv_obj_t *ui_home = NULL;lv_obj_t *ui_title = NULL;lv_obj_t *ui_yearmonthdate = NULL;lv_obj_t *ui_hourminsecond = NULL;lv_obj_t *ui_humitygraph = NULL;lv_obj_t *ui_humityvalue = NULL;lv_obj_t *ui_temperature = NULL;lv_obj_t *ui_temperaturevalue = NULL;lv_obj_t *ui_co2 = NULL;lv_obj_t *ui_co2value = NULL;lv_obj_t *ui_aqi = NULL;lv_obj_t *ui_aqivalue = NULL;
// event funtions

// build funtions

void ui_home_screen_init(void)
{
ui_home = lv_obj_create(NULL);
lv_obj_remove_flag( ui_home, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_title = lv_label_create(ui_home);
lv_obj_set_width( ui_title, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_title, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_title, 0 );
lv_obj_set_y( ui_title, -140 );
lv_obj_set_align( ui_title, LV_ALIGN_CENTER );
lv_label_set_text(ui_title,"STONEI Studio");
lv_obj_set_style_text_color(ui_title, lv_color_hex(0xFF9900), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_title, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_yearmonthdate = lv_label_create(ui_home);
lv_obj_set_width( ui_yearmonthdate, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_yearmonthdate, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_yearmonthdate, 0 );
lv_obj_set_y( ui_yearmonthdate, -110 );
lv_obj_set_align( ui_yearmonthdate, LV_ALIGN_CENTER );
lv_label_set_text(ui_yearmonthdate,"2025. 11. 09. Sun");

ui_hourminsecond = lv_label_create(ui_home);
lv_obj_set_width( ui_hourminsecond, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_hourminsecond, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_hourminsecond, 0 );
lv_obj_set_y( ui_hourminsecond, -80 );
lv_obj_set_align( ui_hourminsecond, LV_ALIGN_CENTER );
lv_label_set_text(ui_hourminsecond,"23:19:00");

ui_humitygraph = lv_arc_create(ui_home);
lv_obj_set_width( ui_humitygraph, 80);
lv_obj_set_height( ui_humitygraph, 80);
lv_obj_set_x( ui_humitygraph, 0 );
lv_obj_set_y( ui_humitygraph, -10 );
lv_obj_set_align( ui_humitygraph, LV_ALIGN_CENTER );
lv_arc_set_value(ui_humitygraph, 20);

ui_humityvalue = lv_label_create(ui_humitygraph);
lv_obj_set_width( ui_humityvalue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_humityvalue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_humityvalue, LV_ALIGN_CENTER );
lv_label_set_text(ui_humityvalue,"20%");

ui_temperature = lv_obj_create(ui_home);
lv_obj_set_width( ui_temperature, 140);
lv_obj_set_height( ui_temperature, 50);
lv_obj_set_x( ui_temperature, 0 );
lv_obj_set_y( ui_temperature, 60 );
lv_obj_set_align( ui_temperature, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_temperature, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_temperaturevalue = lv_label_create(ui_temperature);
lv_obj_set_width( ui_temperaturevalue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_temperaturevalue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_temperaturevalue, LV_ALIGN_CENTER );
lv_label_set_text(ui_temperaturevalue,"25.0");

ui_co2 = lv_obj_create(ui_home);
lv_obj_set_width( ui_co2, 80);
lv_obj_set_height( ui_co2, 50);
lv_obj_set_x( ui_co2, 30 );
lv_obj_set_y( ui_co2, 121 );
lv_obj_set_align( ui_co2, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_co2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_co2value = lv_label_create(ui_co2);
lv_obj_set_width( ui_co2value, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_co2value, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_co2value, LV_ALIGN_CENTER );
lv_label_set_text(ui_co2value,"25.0");

ui_aqi = lv_obj_create(ui_home);
lv_obj_set_width( ui_aqi, 50);
lv_obj_set_height( ui_aqi, 50);
lv_obj_set_x( ui_aqi, -45 );
lv_obj_set_y( ui_aqi, 121 );
lv_obj_set_align( ui_aqi, LV_ALIGN_CENTER );
lv_obj_remove_flag( ui_aqi, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_aqivalue = lv_label_create(ui_aqi);
lv_obj_set_width( ui_aqivalue, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_aqivalue, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_aqivalue, LV_ALIGN_CENTER );
lv_label_set_text(ui_aqivalue,"25.0");

}

void ui_home_screen_destroy(void)
{
   if (ui_home) lv_obj_del(ui_home);

// NULL screen variables
ui_home= NULL;
ui_title= NULL;
ui_yearmonthdate= NULL;
ui_hourminsecond= NULL;
ui_humitygraph= NULL;
ui_humityvalue= NULL;
ui_temperature= NULL;
ui_temperaturevalue= NULL;
ui_co2= NULL;
ui_co2value= NULL;
ui_aqi= NULL;
ui_aqivalue= NULL;

}
