// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.4
// LVGL version: 9.1.0
// Project name: ESP32C6

#ifndef UI_HOME_H
#define UI_HOME_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_home
extern void ui_home_screen_init(void);
extern void ui_home_screen_destroy(void);
extern lv_obj_t *ui_home;
extern lv_obj_t *ui_title;
extern lv_obj_t *ui_yearmonthdate;
extern lv_obj_t *ui_hourminsecond;
extern lv_obj_t *ui_humitygraph;
extern lv_obj_t *ui_humityvalue;
extern lv_obj_t *ui_temperature;
extern lv_obj_t *ui_temperaturevalue;
extern lv_obj_t *ui_co2;
extern lv_obj_t *ui_co2value;
extern lv_obj_t *ui_aqi;
extern lv_obj_t *ui_aqivalue;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

